kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0
kubeadmConfigPatches:
- |
  kind: JoinConfiguration
  discovery:
    # Give the node join process up to 15 minutes to complete
    timeout: 15m0s